### ISSUE TITLE
[QUESTION] Does it work with Amazon or Bestbuy?

### ISSUE THREAD

**Issue by Thingyman-DEV** [EricJMarti/inventory-hunter#1]
Thanks for coding this! I'm looking to get an RTX 3070 for my first gaming PC build.
You listed 3 configs here for Newegg, B & H, and MicroCenter. Would it be possible to configure this to work with BestBuy or Amazon?
Thanks!

EDIT: I just saw that you are working on best buy!
Thank you! (I think that the founders edition looks the coolest by far)

**Comment by EricJMarti** [comment]
Yes! I'm currently working on adding Best Buy support, and Amazon is next on my list after Best Buy. I will let you know once  support has been added.

Also, good luck on your first gaming PC build!

**Comment by Diaolou** [comment]
Thanks both! It would be great if the Amazon support was able to support international domains (for example amazon.co.uk).

**Comment by vgoklani** [comment]
best buy support is tricky. you may be better off using their api directly - https://developer.bestbuy.com/

I was trying to buy an RTX 3090, unfortunately the web developers were playing games. The site pauses, makes you wait, then lets you put the item in the cart, then makes you verify your email, and then you can checkout. Unfortunately the item was gone after I went through this process...

**Comment by dk-do** [comment]
> Thanks both! It would be great if the Amazon support was able to support international domains (for example amazon.co.uk).

Yes - this would be great (amazon.de) ;)

**Comment by EricJMarti** [comment]
Got Best Buy working! Also added in RTX 3060 Ti configs for good measure! :)

Working on Amazon now.

**Comment by EricJMarti** [comment]
Experimental Amazon support just added!
