### ISSUE TITLE
[QUESTION] Any plans for discord support?

### ISSUE THREAD

**Issue by rehatiel** [EricJMarti/inventory-hunter#10]
Might be easier for those people who don't have access to a relay server :)

**Comment by Wood578Guy** [comment]
Anyone can have access to a relay server, it's explained in his readme file.  You run it on the same machine as the docker image and can tie it to your Gmail account.

**Comment by rehatiel** [comment]
Yup, I set one up pretty easily.  Would still love discord ;)

**Comment by EricJMarti** [comment]
Great idea! I will look into adding this in the future.

**Comment by rehatiel** [comment]
Thank you, and thank you for writing this!  I know there are many of us that are frustrated by all the scalpers. :)

**Comment by Casamatechs** [comment]
This is actually pretty easy to do thanks to https://github.com/Rapptz/discord.py, shouldn't take much effort to integrate it into the current code

**Comment by EricJMarti** [comment]
See: https://github.com/EricJMarti/inventory-hunter/issues/37#issuecomment-736900742
