### ISSUE TITLE
Can't use the alerter.yaml update on Windows

### ISSUE THREAD

**Issue by MRizkBV** [EricJMarti/inventory-hunter#100]
I believe run.ps1 was not updated to reflect, or handle the new changes. I tried adding -q (also -alerter-config and --alerter-config) path\to\alerter.yaml but Powershell throws in an error expecting email config. 

I do not have the knowledge to edit the run.ps1 myself :/

**Comment by TK-SpartanGolf6** [comment]
I have the same issue. For me it throws out an error saying 
'Missing email argument. 
At C:\(user directory)\inventory-hunter\docker_run.ps1:15 char 24. 
       if (-Not $email) {throw "missing email argument"}'

When I have both a Discord server notification and email notification set. The following is my '.\config\alerters.yaml' config file.
---
alerters:
  discord:
    webhook_url: (webhook I removed so nobody screws with the server)
    mentions:
      - @everyone
  email:
    sender: (email I removed so nobody screws with my email)
    recipients:
      - (email I removed so nobody screws with my email)
      - (email I removed so nobody screws with my email)
      - (email I removed so nobody screws with my email)
    relay: 127.0.0.1
...

**Comment by MRizkBV** [comment]
@TK-SpartanGolf6 Yea, same error here.

**Comment by EricJMarti** [comment]
This was added in: https://github.com/EricJMarti/inventory-hunter/commit/41a16f614990756b8b161e644bf5abf0883d0c06

Please run `git pull` and use the `-AlerterConfig` argument with `docker_run.ps1`.
