### ISSUE TITLE
Running docker_run.ps1 with an Amazon config crashes instantly. No logs that I can see.

### ISSUE THREAD

**Issue by sauce89** [EricJMarti/inventory-hunter#102]
latest: Pulling from ericjmarti/inventory-hunter
Digest: sha256:e04780a1a2bfebb5cd7123bac056eeb0c85f8053165440b18b6ad1bb663f2d34
Status: Image is up to date for ericjmarti/inventory-hunter:latest
docker.io/ericjmarti/inventory-hunter:latest
cb7702435a3810138f2edce1f5691b5bbd17600a0261b20c0277ed20403d1e3d

started docker container named amazon_rtx_3080

view the status of this container using the following command:
$ docker ps -a -f name=amazon_rtx_3080

CONTAINER ID   IMAGE                                COMMAND                  CREATED                  STATUS                  PORTS     NAMES
cb7702435a38   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   Less than a second ago   Up Less than a second             amazon_rtx_3080

view logs for this container using the following command:
$ docker logs -f amazon_rtx_3080

PS C:\Users\sauce\3080\inventory-hunter> docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS     NAMES
b8a3bb8d052a   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   10 minutes ago   Up 10 minutes             bestbuy_rtx_3080
15d413e46e86   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   11 minutes ago   Up 11 minutes             microcenter_rtx_3080
ceac9acadf87   ericjmarti/inventory-hunter:latest   "bash /src/run.bash …"   11 minutes ago   Up 11 minutes             newegg_rtx_3080
PS C:\Users\sauce\3080\inventory-hunter>

**Comment by EricJMarti** [comment]
Can you run `git pull` to get the latest code and try again? After running `docker_run.bash` or `docker_run.ps1`, you should see a log directory get created with one log file per container. If the container exits immediately after getting the latest code, can you check the log file for any exceptions?

**Comment by sauce89** [comment]
Took a look at the log and it looks like I made a mistake in the config. I had the max_price in the wrong place. Apologies. Good to see the log files in one folder!
