### ISSUE TITLE
Failing to start Discord alerter

### ISSUE THREAD

**Issue by TK-SpartanGolf6** [EricJMarti/inventory-hunter#105]
I have an alert set up for discord, when I run the command to start the scraping, it scrapes correctly but fails to start the discord alerter. Here's the command I am using to start the docker: './docker_run.bash -c ./config/bestbuy_rtx_3080.yaml -a discord -w (webhook)'. I have modified that './config/bestbuy_rtx_3080.yaml' file so that it includes more links to scrape and shortened the scaping time. The '(double underscore) in this post is some type of formatting, but in the error it is two underscores together.

Here is the error I get when it tries to start the Discord alerter. 
'Traceback (most recent call last):
    File '/src/alerter/common.py", line 38, in (double underscore)call(double underscore)
       alerter(**kwargs)
    File "/src/alerter/discord.py", line 37, in (double underscore)call(double underscore)
       "content": mention or None,
UnboundLocalError: local variable 'mention' referenced before assignment

**Comment by EricJMarti** [comment]
This is fixed in: https://github.com/EricJMarti/inventory-hunter/commit/7307136506ef4ec422ba83c57b5d8e11cf4b3d5a

The fix is building and should be available on Docker Hub in about 20 minutes.
