### ISSUE TITLE
Disc Space at 100%

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#127]
I installed the base version of Raspberry Pi OS when setting up Inventory-Hunter.  I am using a 16gb SD card on a raspberry pi 3.  After getting this program set up and updating the OS, I had almost 8 gb of unused space.  After running this program for 2 days I am out of space and used 100% of my 16gb.  Is there a way to clear the cache or stopping it from using so much disc space?  I do a df -h command and I am at all 16gb used in the /dev/root directory.  Thoughts??

**Comment by bluecow82** [comment]
You're lucky. I have the 32gb card on a Pi 4, and running 6 images, it fills up after about 3 hours. I started being more selective with the links I'm having it check, but I have a feeling it has something to do with the Chromium issue detailed at #120 . Haven't been able to figure out a fix yet, hoping someone comes up with an idea.

**Comment by danazc77** [comment]
So how do you clear up space again?   I cant imagine I have to reinstall raspberry pi OS every few hours and reinstall docker snd this code.   Is there a command to run to delete the stored caching??

**Comment by EricJMarti** [comment]
When you run inventory-hunter, it should create a `data` and `log` directory. Can you tell me how large these two directories are? I suspect that something is logging extensively.

**Comment by danazc77** [comment]
Log folder is at 22.2 Mb
Data folder is at 2.5 Mb

I have reinstalled the OS 3 times now because after a day it fills up the 16 gb card.  On initial set up I usually have around 7-8 gb left after installing OS and Inventory Hunter.   Not sure what is getting stored literally in hours to fill up a 16 or 32 gb card.  I cant even open a browser window now since there is no storage left.  As a side not inventory hunter is literally the only program on the OS as there are all fresh OS installs.

**Comment by danazc77** [comment]
I noticed outside of inventory hunter in the Proc folder there are thousands of folders.

**Comment by danazc77** [comment]
![Uploading E0B0005D-7163-4B62-9E14-E2C4E4CD78B5.jpeg…]()

**Comment by bluecow82** [comment]
> So how do you clear up space again? I cant imagine I have to reinstall raspberry pi OS every few hours and reinstall docker snd this code. Is there a command to run to delete the stored caching??

Stopping all the docker images appears to get rid of all that temporary data. The I just restart them.

**Comment by bluecow82** [comment]
> When you run inventory-hunter, it should create a `data` and `log` directory. Can you tell me how large these two directories are? I suspect that something is logging extensively.

The files that grow (at least on my end), are located here:
```
root@raspberrypi:/home/pi# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        27G   27G     0 100% /
devtmpfs        3.8G     0  3.8G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  394M  3.5G  10% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/mmcblk0p6  253M   54M  199M  22% /boot
tmpfs           788M  4.0K  788M   1% /run/user/1000
overlay          27G   27G     0 100% /var/lib/docker/overlay2/ab433ae4dbf140bd0e8a2976d99881c2b2129975b47b0ecd1df97885034600e4/merged
overlay          27G   27G     0 100% /var/lib/docker/overlay2/ab59418956171e5e3f495312014a039b4d1e80ae20bf864d476298f794f49ecf/merged
overlay          27G   27G     0 100% /var/lib/docker/overlay2/5ee33b15f822cdffc3f53b4f1a2417fc2cc72f9662e2a4e8b54c82083e41258e/merged
overlay          27G   27G     0 100% /var/lib/docker/overlay2/546f6ecbafcae22ef4b663cd61278ff6fdc8bac6ea1d440ad06c325b234e7e5e/merged
overlay          27G   27G     0 100% /var/lib/docker/overlay2/50eca644c55c14fe8ab4b6098434d344cfe2d5047e14e16c38540f0203c10fa7/merged
overlay          27G   27G     0 100% /var/lib/docker/overlay2/211a23b7155312c8ff45a674dbdc6e0fbf3f7cd624580cdb7fc0dbe4da3040fd/merged

```

**Comment by bluecow82** [comment]
It appears I found a way to slow this down dramatically, by disabling the Boot to Desktop function of the Pi. 
It also cleared up the Chromium issue (#120), tho the XSERV issue (#126) still persists.
Of course, this is only useful if you can do without the Desktop.

**Comment by danazc77** [comment]
How do you turn off boot to desktop.  Works for me.  I access via ssh anyways.

**Comment by bluecow82** [comment]
`sudo raspi-config`
Option 1, then Option S5. (for me at least)

**Comment by danazc77** [comment]
@bluecow82 How do you set it up to auto restart the dockers each day so I don't have to do it manually?  THanks for all your help by the way.

**Comment by bluecow82** [comment]
I created a bash script that runs the processes I want to run and one that stops them. Then I use cron:
`$ crontab -e`
If you just want a quick restart of the processes, you can do something like:
`30 2 * * * ./inventory-stop && ./inventory-start` , where inventory-stop and inventory-start are the two bash scripts. This makes all the processes stop and then start, each day at 2:30AM.

**Comment by danazc77** [comment]
Ok thanks but that seems to be more complicated than I had hoped for.  I will just do it manually.  I just did it and yes over 7gb unused for now.

**Comment by ShepLT1** [comment]
Any fixes for this that still allows the use of Desktop? From my log directory txt files it seems like Amazon and Bestbuy containers are the culprit as they are experiencing the chromium error

**Comment by EricJMarti** [comment]
Can you try again with the latest image?

I undid a recent change I made that I think is causing this issue: https://github.com/EricJMarti/inventory-hunter/commit/121c4c5626ccfe260861ab21433287d75869d695

**Comment by ShepLT1** [comment]
> Can you try again with the latest image?
> 
> I undid a recent change I made that I think is causing this issue: [121c4c5](https://github.com/EricJMarti/inventory-hunter/commit/121c4c5626ccfe260861ab21433287d75869d695)

That did the trick! Thanks Eric
