### ISSUE TITLE
Page crash after running for brief time.

### ISSUE THREAD

**Issue by Wood578Guy** [EricJMarti/inventory-hunter#13]
When I build docker image from latest, my newegg container runs for a bit, then gets a page crash error, and then all subsequent scrapes fail.

My old docker  container from a previous build w/ newegg config still works fine.

Running my bhphoto config with latest build works just fine also.

Full log file here:
[ba0bae8423d168c965be026f7338fcbdf5c5bfd9a48e4a584d6fccdbef2c4109-json.log](https://github.com/EricJMarti/inventory-hunter/files/5612263/ba0bae8423d168c965be026f7338fcbdf5c5bfd9a48e4a584d6fccdbef2c4109-json.log)

```
E2020-11-29 13:43:51,824 gigabyte-geforce-rtx-3070-gv-n3070eagle-oc-8gd: caught exception during request: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=83.0.4103.116)

E2020-11-29 13:43:51,824 gigabyte-geforce-rtx-3070-gv-n3070eagle-oc-8gd: scrape failed
E2020-11-29 13:43:53,610 gigabyte-geforce-rtx-3070-gv-n3070gaming-oc-8gd: caught exception during request: Message: invalid session id

E2020-11-29 13:43:53,610 gigabyte-geforce-rtx-3070-gv-n3070gaming-oc-8gd: scrape failed
```

**Comment by EricJMarti** [comment]
This looks related to a recent change I made to use the chrome webdriver instead of python requests module. Thus, I rolled back the change to restore the old behavior.

Can you tell me about the hardware you are using? Is it a Raspberry Pi? If so, which model?

**Comment by Wood578Guy** [comment]
I'm not using an R Pi.  

I'm running Ubuntu 18.04 server on XCP-ng hypervisor with Intel E5-2690 v4 processors.

**Comment by EricJMarti** [comment]
Nice setup! How much memory is available to the container? One thing I noticed on my machine is that memory usage skyrocketed after the chrome webdriver change (from ~30 MB to ~0.5 GB total per container). So it's very possible that the crash was related to memory usage.

**Comment by Wood578Guy** [comment]
Chrome?  Lots of memory usage?  Surely not...  

I have 4GB allocated to this VM - would think that should be plenty?

With latest code I see this usage...unfortunately I didn't look at this for Chrome webdriver, and I blew that image away, and I don't know how to go back and rebuild it.
```
NAME                CPU %               MEM USAGE / LIMIT
bhphoto_rtx_3070    0.92%               40.2MiB / 3.822GiB
newegg_rtx_3070     4.79%               39.42MiB / 3.822GiB
```

**Comment by EricJMarti** [comment]
I investigated this further. It turns out that keeping an instance of chromium running can result in strange behavior over time (e.g. chromium crashes but the chromedriver keeps running). So for now, I limited the use of chromium to retailers such as Best Buy.
