### ISSUE TITLE
[Question] Windows friendly tutorial for noobs?

### ISSUE THREAD

**Issue by 210palafox** [EricJMarti/inventory-hunter#14]
Hello Eric, Thank you for this awesome script. I'm attempting to run it on my windows computer. I managed to get docker and git working in powershell. Got as far as step 3 but I keep getting the following errors.

```
PS C:\Users\steve\inventory-hunter> docker run docker_run.bash -c "config.yaml" -e "test@gmail.com" -r 192.168.0.1
Unable to find image 'docker_run.bash:latest' locally
docker: Error response from daemon: pull access denied for docker_run.bash, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
PS C:\Users\steve\inventory-hunter> docker run inventory-hunter                                                         usage: run.py [-h] [-c CONFIG] [-e EMAIL [EMAIL ...]] -r RELAY [-v]
run.py: error: argument -c/--config: can't open 'config.yaml': [Errno 2] No such file or directory: 'config.yaml'
PS C:\Users\steve\inventory-hunter>
```

Obviously, I don't have much experience running python scripts. What am I doing wrong?

**Comment by EricJMarti** [comment]
Someone else asked the same question: https://github.com/EricJMarti/inventory-hunter/issues/6#issuecomment-735319211

I am planning to update the README.md once I test everything on Windows.

**Comment by Trug42** [comment]
Same challenges here. Thanks in advance for the Windows update once you get it ready, and thanks for all the work on the project!

**Comment by stiggy87** [comment]
I just wanted to give my 2cents on how I got it to work on Windows for me.

1. Have to have WSL2 setup (I used Debian)
2. Setup Docker for Windows for it (it includes integration to WSL)
3. After you install both, in the Terminal clone the repo and build for docker
4. Set yourself to root (sudo su)
5. Build the docker image (I was never able to build without it due to some weird dependencies)
6. Run the bash script

You can monitor outputs and what not in the Docker program on WIndows (see screenshot).
![image](https://user-images.githubusercontent.com/565013/100927194-c8e8a180-34a1-11eb-9adf-eae2107a4fae.png)

I just got it to work, so my steps are probably not fully fleshed out, and if someone wants to refine it that would be helpful.

**Comment by ulbhudda** [comment]
> I just wanted to give my 2cents on how I got it to work on Windows for me.
> 
> 1. Have to have WSL2 setup (I used Debian)
> 2. Setup Docker for Windows for it (it includes integration to WSL) -  Make sure you have WSL resource set to your WSL image
> 3. After you install both, in the Terminal clone the repo
> 4. Set yourself to root (sudo su)
> 5. Build the docker image (I was never able to build without it due to some weird dependencies)
> 6. Run the bash script
> 
> You can monitor outputs and what not in the Docker program on WIndows (see screenshot).
> ![image](https://user-images.githubusercontent.com/565013/100927194-c8e8a180-34a1-11eb-9adf-eae2107a4fae.png)
> 
> I just got it to work, so my steps are probably not fully fleshed out, and if someone wants to refine it that would be helpful.

Thanks for these initial steps, I was interested to try this out as well. Will take a look hopefully after work.

**Comment by ulbhudda** [comment]
@stiggy87 thanks for these initial steps, I was interested in running this method as well. I will hopefully try out this method once I am done with work

**Comment by 210palafox** [comment]
also worked for me. Unfortunately, they only released bundles. Is there a
way to make it respond with audio instead of an email? I have some
programming knowledge but i dont know if that would be a native function or
need some kind of api.

**Comment by LapCheong** [comment]
Stuck at the run.py: error: argument -c/--config: can't open 'config.yaml': [Errno 2] No such file or directory: 'config.yaml'


![Capture](https://user-images.githubusercontent.com/49017659/100956157-d14ce500-3552-11eb-92e0-386d94112097.JPG)

**Comment by 210palafox** [comment]
I just put the full file path. Not sure why ./ Wouldn't work.

**Comment by bruttal361** [comment]
> Stuck at the run.py: error: argument -c/--config: can't open 'config.yaml': [Errno 2] No such file or directory: 'config.yaml'
> 
> ![Capture](https://user-images.githubusercontent.com/49017659/100956157-d14ce500-3552-11eb-92e0-386d94112097.JPG)

I have the same issue as you do. not sure why it can't open the config file.

**Comment by EricJMarti** [comment]
@LapCheong The docker container doesn't have access to your filesystem, so you need to copy the config file into the container like this:
```
PS C:\path\to\inventory-hunter> docker run -d --network host -v (Resolve-Path -Path .\config\ps5.yaml):/config.yaml inventory-hunter --email myemail@email.com --relay 127.0.0.1
```

**Comment by LapCheong** [comment]
docker run -d --network host -v C:\Users\kaili\Desktop\inventory-hunter\config\amazon_rtx_3080.yaml:/config.yaml inventory-hunter -a discord -w

This worked, thank you for your help

**Comment by LapCheong** [comment]
> @LapCheong The docker container doesn't have access to your filesystem, so you need to copy the config file into the container like this:
> 
> ```
> PS C:\path\to\inventory-hunter> docker run -d --network host -v (Resolve-Path -Path .\config\ps5.yaml):/config.yaml inventory-hunter --email myemail@email.com --relay 127.0.0.1
> ```

docker run -d --network host -v C:\Users\XXXX\Desktop\inventory-hunter\config\amazon_rtx_3080.yaml:/config.yaml inventory-hunter -a discord -w

**Comment by ulbhudda** [comment]
not sure what I am missing but I cannot seem to map the config file into the docker image it keeps giving the error
'error: /config/ps5.yaml does not exist or is not a regular file'

I have tried replaced commands given by you @EricJMarti and @LapCheong seems I am missing a step. :(

**Comment by ulbhudda** [comment]
> not sure what I am missing but I cannot seem to map the config file into the docker image it keeps giving the error
> 'error: /config/ps5.yaml does not exist or is not a regular file'
> 
> but if I type in
> `nano config/ps5.yaml`
> that pulls up the file just fine.
> 
> I have tried replaced commands given by you @EricJMarti and @LapCheong seems I am missing a step. :(

Ok I got it working had to use the full path for the config file the relative path would just not work. thanks for the tip @210palafox

**Comment by u265v384** [comment]
> > @LapCheong The docker container doesn't have access to your filesystem, so you need to copy the config file into the container like this:
> > ```
> > PS C:\path\to\inventory-hunter> docker run -d --network host -v (Resolve-Path -Path .\config\ps5.yaml):/config.yaml inventory-hunter --email myemail@email.com --relay 127.0.0.1
> > ```
> 
> docker run -d --network host -v C:\Users\XXXX\Desktop\inventory-hunter\config\amazon_rtx_3080.yaml:/config.yaml inventory-hunter -a discord -w
> 
> This worked, just realized what you meant. Cheers

I get an error 
"usage: run.py [-h] [-c CONFIG] [-e EMAIL [EMAIL ...]] -r RELAY [-v]

run.py: error: the following arguments are required: -r/--relay"

when I try run the command in the similar format you do here.

My command line looks like this 

docker run -d --network host -v E:\Users\XXX\RTX\inventory-hunter\config\newegg_rtx_3080.yaml:/config.yaml inventory-hunter -a discord -w https://discord.com/api/webhooks/xxxxxxxxxxxxxxx

I already updated and ran a git pull but to no avail. I was wondering if you came across this when you tried using discord and could assist me, thanks. 

![Untitled](https://user-images.githubusercontent.com/70852016/101265875-c55a5200-370f-11eb-9632-b22a920652eb.png)

**Comment by EricJMarti** [comment]
I created a wiki for Windows users: [Instructions for Windows](https://github.com/EricJMarti/inventory-hunter/wiki/Instructions-for-Windows)

Please `git pull` to retrieve the latest `docker_run.ps1` script.
