### ISSUE TITLE
[Question] Is there a way to test?

### ISSUE THREAD

**Issue by AndrewHulse** [EricJMarti/inventory-hunter#15]
Hello, 
I am fairly new to this sort of code. I was wondering if I could somehow force this program to send me a notification to make sure that it is working correctly? Also, I am looking forward to BestBuy support.

**Comment by EricJMarti** [comment]
I usually test by configuring one item that is currently in stock. For instance:
```
---
refresh_interval: 2 # seconds
urls:
  - https://www.bhphotovideo.com/c/product/1294296-REG/msi_geforce_gtx_1050_ti.html # this one is a test
  - https://www.bhphotovideo.com/c/product/1602755-REG/asus_dualrtx30708g_geforce_rtx_3070_8g.html
  - https://www.bhphotovideo.com/c/product/1602756-REG/asus_strixrtx3070o8_rog_strix_geforce_rtx.html
...
```

**Comment by AndrewHulse** [comment]
Oh I see. For the NewEgg 3070 I set the max price at 800 and it caught the 2070 but it displays this and was not notified. What could be the error?
I start it with:
./docker_run.bash -c ./config/newegg_rtx_3070.yaml -e <my gmail> -r <IP>

I2020-11-29 22:31:41,811 gigabyte-geforce-rtx-2070-super-gv-n207swf3oc-8gd: now in stock at 719.99!
E2020-11-29 22:31:45,142 caught exception
Traceback (most recent call last):
  File "/src/run.py", line 32, in main
    hunt(args, config, driver)
  File "/src/hunter.py", line 121, in hunt
    engine.run()
  File "/src/hunter.py", line 43, in run
    self.scheduler.run(blocking=True)
  File "/usr/local/lib/python3.9/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/src/hunter.py", line 58, in tick
    self.process_scrape_result(s, result)
  File "/src/hunter.py", line 95, in process_scrape_result
    self.send_alert(s, result, f'now in stock at {current_price}!')
  File "/src/hunter.py", line 116, in send_alert
    self.alerter(result.alert_subject, result.alert_content)
  File "/src/hunter.py", line 27, in __call__
    with smtplib.SMTP(self.relay) as s:
  File "/usr/local/lib/python3.9/smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.9/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.9/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

**Comment by fliphil** [comment]
That error is basically saying that when it tries to connect to the SMTP email host, it is not able to find it. It could be a networking error or maybe the email host is not up and running?

**Comment by AndrewHulse** [comment]
How would I go about debugging this?

**Comment by AndrewHulse** [comment]
I tested sendmail <email> and it worked correctly so a bit confused about how I would go about fixing this.

**Comment by fliphil** [comment]
Did you test inside or outside the docker container? Maybe you need to do a port mapping for the container

**Comment by AndrewHulse** [comment]
I believe I tested it outside of the docker image. How would I go about testing inside? And how would I go about port mapping? I'm a beginner.

**Comment by Wood578Guy** [comment]
First, follow the [SMTP tutorial](https://medium.com/swlh/setting-up-gmail-and-other-email-on-a-raspberry-pi-6f7e3ad3d0e) found in the README file.  Make sure it works - then once this works, fully populate the -e and -r arguments in the command.  If you run into add'l troubles, post here.

If you are running the SMTP client in that tutorial on the same machine (Rasp Pi) as the docker container, use `-r 127.0.0.1`.

**Comment by AndrewHulse** [comment]
I had the wrong relay IP. Thank you!
