### ISSUE TITLE
Potential Fixes for sites like Best-buy, and no need for sel driver

### ISSUE THREAD

**Issue by shawnto** [EricJMarti/inventory-hunter#16]
Thanks for this work. I have a merge request I'd like to send up if you'd like to address requests hanging for some sites. Should also prevent needing selenium in most cases, and fix best buy and similar site access issues.

**Comment by EricJMarti** [comment]
Happy to take a look! Please open a pull request so I can merge your changes into the repo.

**Comment by shawnto** [comment]
For the record, had gotten busy so wasn't able to get the request up, but looks like you had found the same solution here:

https://github.com/EricJMarti/inventory-hunter/commit/2ca115a360483d302d11c11c26cc05c35d4500ac#diff-d25e24a8d97a6c8ac16dfc891f0e0e40ef81af06f23ede2d4792526e15dbb3adR45

**Comment by EricJMarti** [comment]
Hey, no worries. I was surprised that's all that was needed to get Best Buy working.

Amazon is a bit smarter though.. still trying to figure out a good workaround. For now, the selenium driver with a headless chromium works okay.
