### ISSUE TITLE
Cannot build docker image. 

### ISSUE THREAD

**Issue by KoopG123** [EricJMarti/inventory-hunter#18]
Alr hey guys. Im new to coding and idk how to do a lot of these things lol. Pls bear w me. Btw thanks Eric for making this its much appreciated. Oh sorry my english is bad too. When building the image it goes to step 9/11 and then says this:

pi@raspberrypi:~/inventory-hunter $ docker build -t inventory-hunter .
Sending build context to Docker daemon  125.4kB
Step 1/11 : FROM python:3.9
 ---> 1e73204649e2
Step 2/11 : RUN apt update
 ---> Using cache
 ---> 059ec8ea530b
Step 3/11 : RUN apt install -y chromium chromium-driver locales locales-all
 ---> Using cache
 ---> c26fc144649c
Step 4/11 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> 836462816cda
Step 5/11 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 3c4e49abe3c4
Step 6/11 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 1a77b4929c62
Step 7/11 : WORKDIR /
 ---> Using cache
 ---> 85ce7862d489
Step 8/11 : COPY requirements.txt /src/requirements.txt
 ---> Using cache
 ---> 407463daf530
Step 9/11 : RUN pip install -r /src/requirements.txt
 ---> Running in e11994b8381a
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Collecting lxml
  Downloading lxml-4.6.2.tar.gz (3.2 MB)
Collecting pyyaml
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting requests
  Downloading requests-2.25.0-py2.py3-none-any.whl (61 kB)
Collecting selenium
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Downloading soupsieve-2.0.1-py3-none-any.whl (32 kB)
Collecting chardet<4,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
Building wheels for collected packages: lxml, pyyaml
  Building wheel for lxml (setup.py): started
  Building wheel for lxml (setup.py): still running...
  Building wheel for lxml (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mh277zjg/lxml/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mh277zjg/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-tbihpvsi
       cwd: /tmp/pip-install-mh277zjg/lxml/
  Complete output (84 lines):
  Building lxml version 4.6.2.
  Building without Cython.
  Building against libxml2 2.9.4 and libxslt 1.1.32
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.9
  creating build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/cssselect.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/__init__.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/builder.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/sax.py -> build/lib.linux-armv7l-3.9/lxml
  creating build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-3.9/lxml/includes
  creating build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/builder.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/clean.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/diff.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-3.9/lxml/html
  copying src/lxml/html/defs.py -> build/lib.linux-armv7l-3.9/lxml/html
  creating build/lib.linux-armv7l-3.9/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-3.9/lxml/isoschematron
  copying src/lxml/etree.h -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/etree_api.h -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-3.9/lxml
  copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-3.9/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-3.9/lxml/includes
  creating build/lib.linux-armv7l-3.9/lxml/isoschematron/resources
  creating build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/rng
  creating build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl
  creating build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-3.9/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.linux-armv7l-3.9
  creating build/temp.linux-armv7l-3.9/src
  creating build/temp.linux-armv7l-3.9/src/lxml
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/local/include/python3.9 -c src/lxml/etree.c -o build/temp.linux-armv7l-3.9/src/lxml/etree.o -w
  gcc: fatal error: Killed signal terminated program as
  compilation terminated.
  Compile failed: command '/usr/bin/gcc' failed with exit code 1
  creating tmp
  cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInit_he3bsco.c -o tmp/xmlXPathInit_he3bsco.o
  cc tmp/xmlXPathInit_he3bsco.o -lxml2 -o a.out
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): still running...
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp39-cp39-linux_armv7l.whl size=514839 sha256=c804dc7fbd8263026447af4b8be22e6e6d3c3db5831efcc487b996c5a42880ad
  Stored in directory: /root/.cache/pip/wheels/69/60/81/5cd74b8ee068fbe9e04ca0d53148f28f5c6e2c5b177d5dd622
Successfully built pyyaml
Failed to build lxml
Installing collected packages: soupsieve, beautifulsoup4, lxml, pyyaml, chardet, urllib3, certifi, idna, requests, selenium
    Running setup.py install for lxml: started

I did this 3 times and it says no docker image file found when doing step 3

Docker image list:
docker image list
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              407463daf530        4 hours ago         1.3GB
python              3.9                 1e73204649e2        11 days ago         694MB
hello-world         latest              851163c78e4a        11 months ago       4.85kB

pls help me to find out what is going on or what im missing.

oh btw docker is installed correctly i checked already.

thanks guys

**Comment by EricJMarti** [comment]
Someone else had a very similar issue where lxml fails to build. Are you using an older Raspberry Pi? It's possible that there isn't enough memory available to build this module.

**Comment by KoopG123** [comment]
thanks for replyin. im using a rasberry pi 3 model b the same one ur using. I read that issue lol. it has 1 gb ram and i checked it to make sure.

**Comment by KoopG123** [comment]
I also got a 32 gb micro sd card that im using. So ik its not storage related problem.

**Comment by Remanent** [comment]
i was also getting a build fail on my raspberry 4 8gb, but i was able to build it on my x5670 ubuntu server (console only) box so i've been using that to run my scrapers instead.

that being said, do you know if the chromium builds your testing now will work on a console only system?

**Comment by Kaveman42** [comment]
I'm getting the same error trying to run the build on my RPie 3 B

**Comment by EricJMarti** [comment]
It seems that the build step for lxml is brittle on some Raspberry Pi's. The build consumes almost all the available memory on my Raspberry Pi 3, but I have never seen it crash.

I'm considering making the lxml install optional (ie: if it builds, awesome.. if not, we can fall back to python's built-in parser). Thoughts?

**Comment by KoopG123** [comment]
Yes I think this is a wonderful idea. (Idk much about this coding stuff FYI) and another thought would be to make other files like the lxml optional if u can do that j incase if it crashes again. I’d hate for you to do all that work and it won’t work for some people. But again that’s just a thought and I think ur idea u presented is amazing. J pls make it easy to follow because for people like me who are below a noob level, it can be easy to follow like you have been doing with your posts now. Thanks man appreciate your work

**Comment by KoopG123** [comment]
Hey Eric, since you Said that the lxml uses a lot of ram I closed the chrome tab I had in the background and it worked for me! So thanks for the suggestion. Anyway, now I will keep this updated if it works on this thread.

**Comment by EricJMarti** [comment]
Just made lxml optional: https://github.com/EricJMarti/inventory-hunter/issues/32#issuecomment-736225183
