### ISSUE TITLE
[QUESTION] Relay

### ISSUE THREAD

**Issue by TylerK999** [EricJMarti/inventory-hunter#2]
What's a suitable relay? Any way to make it work with Gmail?

**Comment by EricJMarti** [comment]
Yes. I used this tutorial to link my Raspberry Pi to Gmail: https://medium.com/swlh/setting-up-gmail-and-other-email-on-a-raspberry-pi-6f7e3ad3d0e

Once configured, you can pass the IP address of your Raspberry Pi (or whatever device you are using) as the relay parameter.

**Comment by TylerK999** [comment]
Thanks! I actually have mine configured similarly (I use msmtp). Maybe my issue is not related to the relay. When I run the script I kicks back a string like "b18811ff512b10713392621db647f05f8e7922bfe0fb2441988c8ee2b8a3ed0d" and then appears to stop.

**Comment by TylerK999** [comment]
Got it! 
Learning about docker today! For anyone reading this, the string is normal when the docker starts. 

So I used the linked tutorial (apologies for not checking the README) and setup my pi to send email that way. IMPORTANT TO NOTE when you setup using those instructions you need to use 127.0.0.1 as your relay address or it will fail.

Its also possible to modify the /etc/postfix/main.cf file to allow you to use the pi IP address but not really necessary for this.

**Comment by EricJMarti** [comment]
Hmm, you may need to change the mynetworks setting in `/etc/postfix/main.cf`. On my Raspberry Pi, I have:
```
mynetworks = 127.0.0.0/8 192.168.0.0/24
```
This allows any device on my local network to use the Raspberry Pi as a relay to send emails programmatically.

**Comment by TylerK999** [comment]
> Hmm, you may need to change the mynetworks setting in `/etc/postfix/main.cf`. On my Raspberry Pi, I have:
> 
> ```
> mynetworks = 127.0.0.0/8 192.168.0.0/24
> ```
> 
> This allows any device on my local network to use the Raspberry Pi as a relay to send emails programmatically.

Thats correct. If you are running inventory-hunter on the same pi as you have email setup you can just use 127.0.0.1 without adding the local (usually 192....)

**Comment by rayontherun** [comment]
Is there a tutorial on how to setup a relay on a Windows 10 PC?

**Comment by EricJMarti** [comment]
> Is there a tutorial on how to setup a relay on a Windows 10 PC?

I haven't tried this myself, but I can think of two ways to configure a relay on Windows:

1. Install Windows Subsystem for Linux (WSL) and choose Debian for step 6 of this tutorial: https://docs.microsoft.com/en-us/windows/wsl/install-win10. Then, you should be able to follow the Raspberry Pi tutorial I linked earlier. My only concern with this approach is that the relay may shut down if you close the Debian terminal window (would need to test to find out).

2. Install Docker on Windows (Docker will also require you to install WSL) and start a relay container based on one of the popular postfix relay Docker images (e.g. https://hub.docker.com/r/freinet/postfix-relay). In retrospect, I probably should have done this on my Raspberry Pi.

**Comment by rayontherun** [comment]
I was able to get this relay working with my Gmail for Windows 10
`https://hub.docker.com/r/tecnativa/postfix-relay`

**Comment by tt1142** [comment]
> I was able to get this relay working with my Gmail for Windows 10
> `https://hub.docker.com/r/tecnativa/postfix-relay`

How were you able to establish a connection to the docker container that has the smtp relay? I've tried multiple variations of localhost IP's and opening ports but keep getting 'connection refused'.

**Comment by theqlam** [comment]
> > I was able to get this relay working with my Gmail for Windows 10
> > `https://hub.docker.com/r/tecnativa/postfix-relay`
> 
> How were you able to establish a connection to the docker container that has the smtp relay? I've tried multiple variations of localhost IP's and opening ports but keep getting 'connection refused'.

I too am having this issue. Specifics below.

`File "/src/hunter.py", line 27, in __call__

with smtplib.SMTP(self.relay) as s:

File "/usr/local/lib/python3.9/smtplib.py", line 253, in __init__

(code, msg) = self.connect(host, port)

File "/usr/local/lib/python3.9/smtplib.py", line 339, in connect

self.sock = self._get_socket(host, port, self.timeout)

File "/usr/local/lib/python3.9/smtplib.py", line 310, in _get_socket

return socket.create_connection((host, port), timeout,

File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection

raise err

File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection

sock.connect(sa)

OSError: [Errno 101] Network is unreachable`

**Comment by EricJMarti** [comment]
In case you are still having issues setting up an SMTP relay, please consider using Discord or Slack: https://github.com/EricJMarti/inventory-hunter/issues/37#issuecomment-736900742
