### ISSUE TITLE
Repeating notifications on alert

### ISSUE THREAD

**Issue by pjneder** [EricJMarti/inventory-hunter#22]
Hello and thanks for the helpful tool! The instructions were straightforward and I had a spare RPi up and running in a short time. An item in my config must have come available for a short while today because I received a notification. Actually I received 79 emails on the same topic with a range of 1-5 mins apart.

My config is modeled after the checked in 6800 XT config. No price limit (which I will change!) and 2s scrape time. In postfix I added an alias that can send a text via email to <number>@mms.att.net. I started the docker with my default email and the alert alias.

Any thoughts on what is happening? What other info could I provide?

Thank you!

**Comment by EricJMarti** [comment]
It sounds like the product was going in and out of stock repeatedly, each time triggering an alert. Some retailers are known to list one unit in stock at a time over the span of an hour or more. Can you attach the logs so I can confirm this is what happened?

**Comment by pjneder** [comment]
[hunter.zip](https://github.com/EricJMarti/inventory-hunter/files/5616502/hunter.zip)

output of: 'docker logs &> hunter.log'

Tell me if you want a different command. This output is not that interesting to me, but you wrote the code so I'm sure you know what you are looking for!

Thanks

**Comment by EricJMarti** [comment]
It definitely looks that way:

```
I2020-11-30 09:59:51,035 msi-radeon-rx-6800-xt-rx-6800-xt-16g: now in stock at 1699.99!
I2020-11-30 10:00:07,034 msi-radeon-rx-6800-xt-rx-6800-xt-16g: still in stock at the same price
I2020-11-30 10:00:23,048 msi-radeon-rx-6800-xt-rx-6800-xt-16g: still in stock at the same price
I2020-11-30 10:00:39,011 msi-radeon-rx-6800-xt-rx-6800-xt-16g: not in stock
I2020-11-30 10:00:55,060 msi-radeon-rx-6800-xt-rx-6800-xt-16g: now in stock at 1699.99!
I2020-11-30 10:01:11,031 msi-radeon-rx-6800-xt-rx-6800-xt-16g: still in stock at the same price
I2020-11-30 10:01:27,025 msi-radeon-rx-6800-xt-rx-6800-xt-16g: still in stock at the same price
I2020-11-30 10:01:42,999 msi-radeon-rx-6800-xt-rx-6800-xt-16g: still in stock at the same price
I2020-11-30 10:01:58,990 msi-radeon-rx-6800-xt-rx-6800-xt-16g: not in stock
I2020-11-30 10:02:15,161 msi-radeon-rx-6800-xt-rx-6800-xt-16g: now in stock at 1699.99!
```

Another possibility is that Newegg was going back and forth between showing their own listing and this scalper's listing.

Nevertheless, this is egregious pricing for a 6800 XT, so I would set the `max_price` config parameter to avoid getting spammed by these listings.

**Comment by amitkumar455** [comment]
Where are you from all guys?

**Comment by pjneder** [comment]
@EricJMarti good point. I didn't realize that NE could host scalper sales like that but obviously is happens. I have now added a max_price option to my config file and restarted the docker.

I also know what to better look for in the future if I get a pile of messages.

Keep up the good work, and let me know if you need any beta testing of scrapers for other sites.

Thanks!
