### ISSUE TITLE
Bestbuy stating Scrap Failed

### ISSUE THREAD

**Issue by KoopG123** [EricJMarti/inventory-hunter#23]
So now this runs perfectly and I get my alerts via email. But for Best Buy, It says scrape failed. It says caught deception during request: got response with status code 403 for https://www.Bestbuy...

Any recommendations? I got the latest files just now and tried it but it didn't work. Thanks

**Comment by EricJMarti** [comment]
I'm still working on getting Best Buy scraping working reliably. I will let you know when you can give it another try.

**Comment by KoopG123** [comment]
oh okay sorry to impose. Thanks for all your work. Any updates for amazon links?

**Comment by EricJMarti** [comment]
I haven't had a chance to look into Amazon. They have similar web scraping protections in place as Best Buy. So once I get Best Buy working, Amazon will likely follow soon after that.

**Comment by alexgraham** [comment]
You sure you did a rebuild after updating to the latest files? I was getting a 403 error for Bestbuy in the previous version pre-Selenium integration. Can you resolve the URL in your device browser?

**Comment by EricJMarti** [comment]
Can you `git pull` the latest code and try again? I think I finally got Best Buy working! Also added Best Buy RTX 3060 Ti configs. :)
