### ISSUE TITLE
Adding functionality for external alerting systems

### ISSUE THREAD

**Issue by ms7m** [EricJMarti/inventory-hunter#24]
How's the idea of making ``Alerter`` more modular on how it sends notifications out?

I can whip up something to make it easier for other people to add custom alerts and expand to different platforms (probably use [an external library for handling the vast majority of them](https://github.com/liiight/notifiers))

Thanks for this project!

**Comment by alexgraham** [comment]
This would be really useful. Discord is another that I think would be useful to add, trying to get that working locally atm.

**Comment by EricJMarti** [comment]
Totally agree. This is something I'm planning to implement.

**Comment by ms7m** [comment]
Took a crack at in PR #34 

Works pretty nicely with existing code

Here is a discord example (Slack should also be easy to implement as well.)
![image](https://user-images.githubusercontent.com/37344632/100708918-27673000-337b-11eb-8cdf-ecc03cbd22f4.png)

Added new arguments to complement which alerter to be chosen + webhook url.
