### ISSUE TITLE
error when building docker

### ISSUE THREAD

**Issue by dnyt84** [EricJMarti/inventory-hunter#26]
Good Morning,

when I am building the docker image I get the following error:

Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.2-py2.py3-none-any.whl (136 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    lxml from https://files.pythonhosted.org/packages/8e/9c/74248ebfd8893bc8ae87abdcc15dd195d01a737ec6e5f91fa503f667e1b9/lxml-4.6.2-cp39-cp39-manylinux1_x86_64.whl#sha256=7e9eac1e526386df7c70ef253b792a0a12dd86d833b1d329e038c7a235dfceb5 (from -r /src/requirements.txt (line 2)):
        Expected sha256 7e9eac1e526386df7c70ef253b792a0a12dd86d833b1d329e038c7a235dfceb5
             Got        5e153b711867e66826c7354753674e4fe4baae5c58dd20681fe4029f004e28fb

    urllib3<1.27,>=1.21.1 from https://files.pythonhosted.org/packages/f5/71/45d36a8df68f3ebb098d6861b2c017f3d094538c0fb98fa61d4dc43e69b9/urllib3-1.26.2-py2.py3-none-any.whl#sha256=d8ff90d979214d7b4f8ce956e80f4028fc6860e4431f731ea4a8c08f23f99473 (from requests->-r /src/requirements.txt (line 4)):
        Expected sha256 d8ff90d979214d7b4f8ce956e80f4028fc6860e4431f731ea4a8c08f23f99473
             Got        69d396d850e63a8aea3d4b22a3ae6197b34574e6264ba8b08cff41f37f0ebc8e

WARNING: You are using pip version 20.2.4; however, version 20.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r /src/requirements.txt' returned a non-zero code: 1
[root@localhost inventory-hunter]#

**Comment by EricJMarti** [comment]
Can you `git pull` and try again using this build command instead:
```
$ docker build --build-arg requirements=requirements_lite.txt -t inventory-hunter .
```
