### ISSUE TITLE
Multiple email addresses 

### ISSUE THREAD

**Issue by Instah** [EricJMarti/inventory-hunter#28]
How does one input multiple emails when running the line of code shown in readme file ? (If possible)

**Comment by pjneder** [comment]
@Instah you can use something like:
./docker_run.bash -c ./config/newegg_rx_6800_xt.yaml -r 127.0.0.1 -e <primaryemail>@gmail.com -e <secondaryemail>@gmail.com -e <aliasdefinedinpostfix>

Something like that. My understanding is to use the default/primary email as the first entry and then any other aliases.

**Comment by EricJMarti** [comment]
@pjneder Yes, that's exactly it. I still need to document this behavior... currently working on a wiki.

Support for Discord/Slack was added today in case you folks are interested in that instead of email.
