### ISSUE TITLE
Relay IP Address

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#29]
First of all Thank you Eric!  I am fortunate to have a raspberry pi laying around that I am not using for Retro Pi and this is a great idea.  I have been trying for 2 months to get a 3080 with no luck.  I am hoping this helps me obtain a 3080 as my 1080 is feeling its age.  With that being said, I have dabbled in this stuff a little bit with some work stuff and also retro pi, but I was curious on the "Relay IP Address".  Is this the IP assigned to my raspberry pi or my main WAN IP or am I missing it entirely?  Thanks in advance!

**Comment by EricJMarti** [comment]
The relay IP address should be the local IP address of the Raspberry Pi. If that doesn't work and you are running docker on the same host that's configured to send emails, try the loopback IP address (127.0.0.1).
