### ISSUE TITLE
[Question] Under what circumstance does it send an email?

### ISSUE THREAD

**Issue by sigavg** [EricJMarti/inventory-hunter#31]
(I'm new to coding like this, so sorry if this isn't clear)
I started two docker containers successfully, and when I run the commands to show the logs they are accurately telling me the status of the item. As suggested in another question, I added a product that was in stock for a test email, and it says it's in stock at the same price but I haven't received an email for even the first run, so I wanted to know what event triggers an email. I followed the readme all the way through and typed the email and my ip correctly.
In case this is relevant: I'm not using raspberrypi, I did the wsl2 thing and am typing in ubuntu from the microsoft store

Edit: forgot to include this question, if we're looking for different items (Example: I'm searching for the 3070 at best buy but the only config file in the folder was for the 3080) I would replace the 3080 link with the 3070 link from best buy, or are there different steps to follow?

**Comment by I-press-buttons** [comment]
I needed to look into /var/log/syslog for the mail attempt that was failing. Have you check any additional log messages?

**Comment by sigavg** [comment]
what's the command for that? I did $ docker logs -f bhphoto_rtx_3070 to get what I saw

**Comment by EricJMarti** [comment]
@sigavg In case you are still having issues setting up an SMTP relay, please consider using Discord or Slack: https://github.com/EricJMarti/inventory-hunter/issues/37#issuecomment-736900742
