### ISSUE TITLE
SMTP Relay Directory

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#37]
Should I be setting up the SMTP relay in the Base Directory or within the hunter-inventory directory after installing Docker.  Sorry new to this and learning.  Thanks!

**Comment by alexgraham** [comment]
It'll normally be outside of Docker and the project. For Mac I've been using Postfix, I think hmailserver works for Windows.

If you're struggling to get it working I would wait until later for the Discord/Slack/webhook developments to be merged as that will make things much easier to setup and won't require any email stuff at all. Keep an eye out for any new commits later today once those additions are integrated.

**Comment by EricJMarti** [comment]
Discord and Slack support is finally here! A big thanks to @ms7m for his contribution to this project!

If you are interested in this feature, your run command will look like this:
```
$ ./docker_run.bash -c ./config/newegg_rtx_3070.yaml -a discord -w https://discord.com/api/webhooks/...
```

**Comment by rehatiel** [comment]
Hey Eric, getting this with my attempt at running discord:

root@invhunter:~/inventory-hunter# docker logs -f newegg_rtx_3070
usage: run.py [-h] [-c CONFIG] [-e EMAIL [EMAIL ...]] -r RELAY [-v]
run.py: error: the following arguments are required: -r/--relay

**Comment by EricJMarti** [comment]
@rehatiel Did you `git pull` the latest code and rebuild the docker container?

**Comment by rehatiel** [comment]
Sure did bud :)

**Comment by rehatiel** [comment]
Oh.. rebuild.. no

**Comment by theqlam** [comment]
@EricJMarti  Dude, the Discord webhooks works perfectly. Just need to double check my phone notification settings.
