### ISSUE TITLE
Asking for username and password when trying to git clone 

### ISSUE THREAD

**Issue by KoopG123** [EricJMarti/inventory-hunter#38]
Hey Eric, you said to rebuild the docker image so when I try to git clone it tells me to put in an email and password. What do I put for that?

**Comment by KoopG123** [comment]
Here is the code:
pi@raspberrypi:~ $ git clone https://github.com/EricJMarti/inventory-hunter.
Cloning into 'inventory-hunter.'...
Username for 'https://github.com':

**Comment by EricJMarti** [comment]
Do you have a trailing period in the link?

**Comment by KoopG123** [comment]
yes I do.

**Comment by KoopG123** [comment]
I even tried a git pull method and that did not work as you said in the previous 'issue'. btw thanks for making best buy work.

**Comment by EricJMarti** [comment]
It's strange for git to be asking you for a password on a clone. Have you tried git cloning in a new directory (in other words, pulling a brand new copy of the code)?

**Comment by arman-de** [comment]
Hello, 
I am having the same issue with the user name and password.
I just pulled the clone not too long ago but it failed because my SD card didn't have enough storage, so I put Raspbian on a new SD card and tried again but now I'm being aske for a password.
Any suggestions?

**Comment by arman-de** [comment]
Ok work around: fork the code and then use git with the link after forking to you account

**Comment by SAMLCSE** [comment]
Hello, Download the repo to your Raspberry Pi as a ZIP and then start terminal on downloaded directory.

**Comment by danazc77** [comment]
Same issue here... I need a username and password to do git clone... I also noticed the '.' no longer has a space at the end which changed from yesterday.

**Comment by danazc77** [comment]
Any ideas here. I have been trying to do this build the last 2 nights.  First tried SMTP and got to the end but then couldn't get emails to work, then tried Discord and never got notifications on Discord, so I am starting over now and now I am getting prompted for user id and password which this step has never caused an issue the last 2 days so something has changed.  Please help. Thank you!

**Comment by bapcruzgithub** [comment]
I left out the period and it seems like it downloaded ok. Still need to verify though.  
.
One thing that changed with the new setup is now emails are no longer going out (after I worked a long time to get them working in the previous version within hunter.py). :)

**Comment by danazc77** [comment]
I left out the period as majorhavocgit suggested and it all worked for me.

**Comment by EricJMarti** [comment]
Looks like I had a trailing period in the git clone command in README.md. This was not intentional. Sorry about that!
