### ISSUE TITLE
Refresh Not Working at Specified Rate

### ISSUE THREAD

**Issue by adrianvasu** [EricJMarti/inventory-hunter#39]
Hi Eric, Found your code online and it is awesome! I've got a bunch of config files that seem to be working. The only thing I'm noticing is that it seems like there is a 90 second refresh between these checking to see if they are in stock? I'm attaching a screenshot of my docker logs. Not a big issue just curious if you know of a quick fix.

P.S. I do have the refresh interval set to 2 as you do in your examples.
![image](https://user-images.githubusercontent.com/32743531/100834110-e9c4de80-3430-11eb-96df-5886881d8a75.png)

**Comment by EricJMarti** [comment]
Can you try updating your copy of the code and rebuilding the docker container? I fixed this last night.
