### ISSUE TITLE
[QUESTION] Docker image build 

### ISSUE THREAD

**Issue by Angel-AlvarezV** [EricJMarti/inventory-hunter#4]
Hello I have problems when executing the .bash it appears "the inventory-hunter docker image does not exist ... please build the image and try again" but I already made the image and I don't know what to move it, it would be very kind of you if you supported me maybe I did something wrong but I follow all the steps you have

**Comment by EricJMarti** [comment]
The first thing that comes to mind is that maybe the docker image was built with a different name than "inventory-hunter". Can you check the output of this command: `docker images inventory-hunter`

**Comment by Angel-AlvarezV** [comment]
Yes, i think is that i don't know why

![IMG_20201122_165248](https://user-images.githubusercontent.com/21070209/99922081-4f9fc080-2ce3-11eb-90e6-3a19c75b8f31.jpg)

**Comment by EricJMarti** [comment]
It appears the docker build command failed with "pip ... returned a non-zero code: 139". Never seen this error before!

A quick Google search suggests that something is segfaulting during the build.

Which model of Raspberry Pi are you using? I used a Raspberry Pi 3 Model B, which has 1 GB of RAM. It is possible that models with less memory aren't capable of building this Docker image (you can check how much memory your Raspberry Pi has with the `free -h` command).

**Comment by Angel-AlvarezV** [comment]
> It appears the docker build command failed with "pip ... returned a non-zero code: 139". Never seen this error before!
> 
> A quick Google search suggests that something is segfaulting during the build.
> 
> Which model of Raspberry Pi are you using? I used a Raspberry Pi 3 Model B, which has 1 GB of RAM. It is possible that models with less memory aren't capable of building this Docker image (you can check how much memory your Raspberry Pi has with the `free -h` command).

Ohhh... Yeah i think is that i have de first model with 500Mb lol, well thanks for the repply ill try to buy other with more Ram!

**Comment by EricJMarti** [comment]
Other users reported similar build issues, so I make the lxml dependency optional: https://github.com/EricJMarti/inventory-hunter/issues/32#issuecomment-736225183
