### ISSUE TITLE
Blocked from NewEgg.com

### ISSUE THREAD

**Issue by SAMLCSE** [EricJMarti/inventory-hunter#40]
I have a error when accessing Newegg.com. _**We're sorry, but our systems have detected the possible use of an automated program to visit Newegg.com**_

Any solution please

**Comment by Drumlord90** [comment]
Same here, mine got flagged after about 24 hours, and have to wait another 24 to try again.

**Comment by SAMLCSE** [comment]
I Change refreshing time 2 seconds to 12 seconds works perfectly.
