### ISSUE TITLE
[request] adding newegg combos

### ISSUE THREAD

**Issue by sohailoo** [EricJMarti/inventory-hunter#45]
adding newegg combos to so we can also search stock for them because its the best way to get cards now 
this is the link for 3080 
https://www.newegg.com/p/pl?d=3080&N=31001489&isdeptsrh=1

i tried adding them to the config but i get [missing buy box]

**Comment by EricJMarti** [comment]
Done: https://github.com/EricJMarti/inventory-hunter/commit/46841784070ef50b42e4a81d407a1c63e08c2e27

I tested using this combo deal: https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205279

**Comment by sohailoo** [comment]
thanx your doing all of this for us for free

**Comment by sohailoo** [comment]
i just downloadded the latest zip and built a new image and deleted the previous one and then tested it with with combo with this combo and got the same error https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205116

`missing combo add to cart button: https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205116
`
