### ISSUE TITLE
Docker Set Up Step #3 and overall process to set up

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#46]
Every time I get to Step #3 of docker set up it doesnt work.  Says user doesn't exist.  As a side note I have a fresh install of raspberry pi os installed and doing everything from my 'pi' account.  Please check my steps where I am going wrong:

All done as logged into 'pi'

1.  Install Raspberry pi OS
2.  Boot up Raspberry Pi and update to latest OS software
3. Install Docker and updates/upgrades.  (Stuck on #3 as mentioned above)
4. git clone of inventory-hunter (asking for login credentials)
5. Tried SMTP to no avail and also discord.  Is discord as easy as just using the webhook url, or do I need to do something else with it.  In the instructions it is stating in the example to set up a json and adding an extension to the url.  I am not sure I need to go this far.

Sorry for maybe the dumb questions, but I have built numerous RetroPi's and have little experience in this set up and been trying feverishly for 2 months to buy 1 simple 3080 gpu and beyond annoyed that it has to come down to me learning coding to buy a gpu.  I am willing to do it, but just need some help as I am struggling. Thanks in advance!

**Comment by EricJMarti** [comment]
Is this the step you get stuck on?
```
sudo usermod -aG docker Pi
```
If so, can you try again with a lowercase 'p' in 'pi'?

**Comment by danazc77** [comment]
Yes.  I have tried pi and Pi.  Says no permissions. I then create a sub user and log in as that user and docker run hello-world works. 
Thanks for all your help. Just been extremely frustrated. Have spent about 10 hours and still at square 1 each try. Wiped clean 4 times now with new pi os.  I have worked with pi’s for years but at a retro pi capacity not this capacity.  I am pretty technical but struggling following when to install what tools.  I preferred smtp than getting discord message but i am at the point to just get it to work.  Thanks so much for all you have done. 


Dana Freiburger262 894 1081

On Wednesday, December 2, 2020, 7:04 PM, Eric Marti <notifications@github.com> wrote:




Is this the step you get stuck on?
sudo usermod -aG docker Pi

If so, can you try again with a lowercase 'p' in 'pi'?
