### ISSUE TITLE
newegg combos 

### ISSUE THREAD

**Issue by sohailoo** [EricJMarti/inventory-hunter#48]
#45 
i just downloadded the latest zip and built a new image and deleted the previous one and then tested it with this combo and got the same error https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205116

missing combo add to cart button: https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205116

**Comment by EricJMarti** [comment]
Hmm, I'm not seeing this issue with that link:
```
I2020-12-03 03:12:15,410 scraper initialized for https://www.newegg.com/Product/ComboDealDetails?ItemList=Combo.4205116
I2020-12-03 03:12:17,910 Product: now in stock at 499.98!
```

When you built the Docker image, did you use the regular build command or the requirements_lite variant?

**Comment by sohailoo** [comment]
the lite variant

**Comment by EricJMarti** [comment]
Just rebuilt my image with requirements_lite.txt and I'm now seeing the issue. Looking into it now.

**Comment by sohailoo** [comment]
thanks and about that issue with amazon scraping 
after i edited the file i get missing title is it normal or there is something wrong 
i used this link 
`W2020-12-03 03:22:04,605 missing title: https://www.amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR7SV3M
`

**Comment by EricJMarti** [comment]
Can you try pulling the latest image from Docker Hub? See: https://github.com/EricJMarti/inventory-hunter/issues/36#issuecomment-738471059

You will need to `git pull` to retrieve the updated `docker_run.bash` script which uses the official image by default. I suspect that the issues you are experiencing are related to the requirements_lite build.
