### ISSUE TITLE
Docker Container Exiting Immediately

### ISSUE THREAD

**Issue by Reagan-K** [EricJMarti/inventory-hunter#5]
When running the given ./docker_run.bash command I get a string with a bunch of characters (which changes every time I run it) and it appears to exit.

When I check to see if any docker containers are currently running (with `docker ps`) nothing shows to be running but when running `docker ps --filter "status=exited"` it shows the containers have already exited.

Is there a log file for errors to look to see what the issue is?

**Comment by EricJMarti** [comment]
Yes, you can use docker to figure out why the container exited immediately. First, find the container with the `docker ps -a` command:
```
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
8d061c172934        inventory-hunter    "python /src/run.py …"   30 seconds ago      Exited (1) 29 seconds ago                       sad_maxwell
```
Then, pass the container name or id to to the `docker logs` command:
```
$ docker logs 8d061c172934
E2020-11-25 12:36:12,920 caught exception
Traceback (most recent call last):
  ...
```
You can also use a UI such as [Portainer](https://github.com/portainer/portainer) to view logs and manage containers.
Please let me know if you have any other questions.

**Comment by Reagan-K** [comment]
That worked perfectly, thank you!
