### ISSUE TITLE
Basic Docker Commands

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#50]
Can someone do a quick list of common Docker Commands for people like myself have a reference?  For example, see what containers are active, how to stop 1 or all of them, how to remove them, etc... I am pretty new to this but I think not for only myself but others this will be great to have for others to be able to make sure the containers are running and how long they have been up, etc...  Also anything you else might suggest as nice to know when up and running.

Thank you to anyone helping on this project.  Never thought I would be dabbling in this just to get a darn gpu.

**Comment by SAMLCSE** [comment]
This is good resources 
https://phoenixnap.com/kb/remove-docker-images-containers-networks-volumes

**Comment by danazc77** [comment]
Awesome! Thank you!
