### ISSUE TITLE
Telegram Bot Notifications

### ISSUE THREAD

**Issue by morganfw** [EricJMarti/inventory-hunter#52]
Hello,
like Discord and Slack, may you add Telegram Bot Notifications (https://core.telegram.org/bots#6-botfather)?

Thank you in advance

**Comment by EricJMarti** [comment]
Added! Big thanks to @dvreed!

Your run command will look like this:
```
./docker_run.bash -a telegram -w <WEBHOOK_URL> -d <CHAT_ID> -c <CONFIG>
```

**Comment by dvreed** [comment]
small correction... the chat ID is a `-i` or `--chat-id`

**Comment by EricJMarti** [comment]
@dvreed Yeah, the python script uses `-i` for the chat ID but `docker_run.bash` was already using `-i` to specify a custom image instead of pulling the latest one from Docker Hub. I should probably change this to make things consistent between the two scripts.
