### ISSUE TITLE
Updating Code Tutorial

### ISSUE THREAD

**Issue by AndrewHulse** [EricJMarti/inventory-hunter#55]
Hello,
I am trying to update my current system with your new updates but not sure how to go about this. Any help would be greatly appreciated. (Would be nice to see this in the readme but mostly just because I'm a beginner lol)

**Comment by danazc77** [comment]
I do agree, what would be common commands to run to make sure we are running the latest versions of docker, inventory-hunter, etc....  I am glad to be up and running and thanks to everyone for your help.  Now lets hope they release some gpu's for once.

**Comment by AndrewHulse** [comment]
Awesome Thank you! Keep up the good work!

**Comment by EricJMarti** [comment]
Big thanks to @thecyberbutler for updating the documentation!
