### ISSUE TITLE
Container status immediately exiting

### ISSUE THREAD

**Issue by Coventry423** [EricJMarti/inventory-hunter#56]
I've been trying to figure this out for a while but I can't understand why my container statuses are exiting right after I create them. I run the `docker logs [ID]` and I get an error `run.py: error: the following arguments are required: -a/--alerter` 
I'm using my email as an alerter type.

**Comment by EricJMarti** [comment]
Are you using the `docker_run.bash` script to start containers? If so, what does your run command look like?

**Comment by Coventry423** [comment]
`./docker_run.bash -c ./config/bestbuy_rtx_3080.yaml -e [email] -r [my raspberry IP]`

**Comment by EricJMarti** [comment]
How recent is the code you are running? Can you try a `git pull` to grab the latest version of the repo?

**Comment by Coventry423** [comment]
Yea I'm actually in the process right now. I used `docker container stop $(docker container ls –aq) && docker system prune –af ––volumes` and then `docker pull ericjmarti/inventory-hunter:latest`

**Comment by Coventry423** [comment]
ok the `git pull` fixed it thanks
