### ISSUE TITLE
Docker pull function not working

### ISSUE THREAD

**Issue by arman-de** [EricJMarti/inventory-hunter#57]
Installing on a laptop running raspberry pi os (LOL), since my raspberry pi 1 model a decided not to work.
I am unable to run docker pull to finish installing.

Input:  _docker pull ericjmarti/inventory-hunter:latest_
output: __latest: _Pulling from ericjmarti/inventory-hunter__
no matching manifest for unknown in the manifest list entries_
Any suggestions?

**Comment by EricJMarti** [comment]
Unfortunately, it doesn't look like it is possible to run this on the original Raspberry Pi without some major hacks. I just tried to add the armv6 platform to the builder, and it failed on the chromium installation step.

Can you try installing Docker Desktop for Windows 10 or macOS? After installing Docker, the `docker_run.bash` script should work as-is on macOS. On Windows, things are a bit more manual right now (still working on a powershell version of `docker_run.bash`). The powershell command for Windows is:

```
PS C:\path\to\inventory-hunter> docker run -d --network host -v (Resolve-Path -Path .\config\ps5.yaml):/config.yaml ericjmarti/inventory-hunter:latest --email myemail@email.com --relay 127.0.0.1
```

**Comment by arman-de** [comment]
I'll give it a shot, thanks!
I actually installed rasbian on a amd based laptop, so im in the process of seeing if it will work on the laptop. If not then i'll just take the windows route.

**Comment by EricJMarti** [comment]
In case you are interested in instructions specific to Windows, see: https://github.com/EricJMarti/inventory-hunter/issues/14#issuecomment-739513439
