### ISSUE TITLE
Test Discord Webhook

### ISSUE THREAD

**Issue by qwoodmansee** [EricJMarti/inventory-hunter#60]
Is there any way to test the webhook i setup? would just like a confirmation that a notification can be sent

**Comment by gavinpirrie** [comment]
One option would be to change the url to something that you know is in stock and increase the max price to encompass it. That should trigger a notification.

**Comment by qwoodmansee** [comment]
That did it! closing issue, thanks.

**Comment by cwoods1294** [comment]
my docker log shows my test item is in stock, but no notifications are coming through to my discord, not sure how to troubleshoot?
