### ISSUE TITLE
Issues with running the docker bash command line with email line

### ISSUE THREAD

**Issue by JakobPiman** [EricJMarti/inventory-hunter#63]
Sorry, really new to coding and working with the Pi itself.  Took a couple of re-formats of my SD card to get my vpn right.  But anyways got my email set up for sending through the SMTP, but when running the bash command line I keep returning the same error.

docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create?name=amazon_rtx_3080: dial unix /var/run/docker.sock: connect: permission denied.

so I did another attempt at a clean install of the docker software and inventory hunter and now get the error below when trying to pull the latest

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/images/create?fromImage=ericjmarti%2Finventory-hunter&tag=latest: dial unix /var/run/docker.sock: connect: permission denied

Any thoughts?  Like I said pretty new to this and have only been able to do some of the step by step tutorial stuff so far and was braching out into this as I am currently looking to upgrade my 1060 gpu and have thus far either been to late or stuck in the loop of trying to check out until I am told well were out of stock again thanks for playing.

**Comment by thecyberbutler** [comment]
Seems like a permissions issue.  Did you run the usermod command from the docker install?

`sudo usermod -aG docker Pi`

**Comment by JakobPiman** [comment]
That was it, sorry for the late response.  Skipped that step initially because I thought my current login was the admin, but I guess i didnt matter?  Anyways thank you!
