### ISSUE TITLE
telegram config

### ISSUE THREAD

**Issue by alkalinelito** [EricJMarti/inventory-hunter#64]
Hi I'm testing the telegram notification, but I'm not sure what to use for webhook url

I have my API token  and my chat id 

most documentation about webhooks involves exposing a webserver to the internet  ?

**Comment by EricJMarti** [comment]
I am not personally familiar with telegram, so I will defer to @dvreed, who implemented telegram support.

**Comment by savageb1ts** [comment]
The webhook URL is the sendMessage API URL with your bot token:
`https://api.telegram.org/bot{BOT_TOKEN}/sendMessage`

Full docker_run.basg command:
`./docker_run.bash -c config/config.yaml -a telegram -w https://api.telegram.org/bot{BOT_TOKEN}/sendMessage -d {CHAT_ID}`

**Comment by alkalinelito** [comment]
Great, thank you
