### ISSUE TITLE
BHPhoto Error Message

### ISSUE THREAD

**Issue by CuppaJava123** [EricJMarti/inventory-hunter#67]
Hi. I am using the Discord webhook method and when I start the script and look at the logs, the same error message keeps looping for all of the out of stock products:
`caught exception during request: got response with status code 429 for <product link>`
followed by:
`scrape failed`
Some lines also say:
`caught exception during request: HTTPSConnectionPool(host='www.bhphotovideo.com', port=443): Read timed out. (read timeout=1)
`
Is this error occurring because the website is detecting the bot, or is it something else? I am using the config file bhphoto_rtx_3080.yaml

**Comment by alexgraham** [comment]
That 429 error code means you're making too many requests: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

If you're using a 2 second interval time I would recommend upping it to 4 seconds to avoid being detected.

**Comment by EricJMarti** [comment]
I just committed a change to increase the read timeout on faster refresh intervals: https://github.com/EricJMarti/inventory-hunter/commit/654af6f881c6bfbebf4d439de71111cd89cf21ef

Please pull the latest image using:
```
$ docker pull ericjmarti/inventory-hunter:latest
```
