### ISSUE TITLE
docker_run.bash Not Found

### ISSUE THREAD

**Issue by MentalMetalhead** [EricJMarti/inventory-hunter#73]
I'm running on a Raspberry pi and I am trying to run the $ ./docker_run.bash -c <config_file> -a <discord_or_slack> -w <webhook_url> and I get file not found.

**Comment by pandamilk** [comment]
Did you make sure you changed directory to the inventory-hunter folder? "./" means in current working directory so if you're not in the folder where the docker_run.bash is located, it'll come up as file not found. 
run "cd inventory-hunter" first and then try it again.

**Comment by MentalMetalhead** [comment]
> Did you make sure you changed directory to the inventory-hunter folder? "./" means in current working directory so if you're not in the folder where the docker_run.bash is located, it'll come up as file not found.
> run "cd inventory-hunter" first and then try it again.

Yes I had and I still keep getting that warning.

**Comment by shattenjager** [comment]
can you run a simple docker command such docker images or docker run hello-world? Are you root? Are using sudo?
