### ISSUE TITLE
Amazon PID's

### ISSUE THREAD

**Issue by danazc77** [EricJMarti/inventory-hunter#78]
I have noticed that the Amazon container has many PID's when Best Buy and New Egg just have 1 PID when running them.  Is there a command I can run or something in the yaml I can change so the PID's aren't racking up on Amazon?  Thanks in advance.

**Comment by EricJMarti** [comment]
@danazc77 This bug was fixed last night. Can you try again with the latest image:

```
$ docker pull ericjmarti/inventory-hunter:latest
```
