### ISSUE TITLE
Simple suggestion + tips for noobs (like me)

### ISSUE THREAD

**Issue by Wood578Guy** [EricJMarti/inventory-hunter#8]
One thing that might be helpful is to have the docker_run.sh name the container it creates the same as the config file.  If I knew how to work Git worth a damn, I'd submit a pull req. for this since I assume it's easy.

Since I was usually creating multiple containers, one for each site, it was then difficult to tell which was for which site.

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
b4ea0984ef2e        inventory-hunter    "python /src/run.py …"   3 minutes ago       Up 3 minutes                            bold_solomon
265636d8ccdb        inventory-hunter    "python /src/run.py …"   20 minutes ago      Up 20 minutes                           sleepy_golick
d6c9da1a5081        inventory-hunter    "python /src/run.py …"   20 minutes ago      Up 20 minutes                           blissful_tharp
```
Tip for noobs -  to display running containers:  `docker ps`

**How do I tell if it's working?**
After running `docker ps` copy the name you want to see if it's working and run `docker logs -f <name>`

Example from the command above: `docker logs -f bold_solomon`

Output - this is what i see when it's working.  If it's not working, you'll find hints here as to why not.
```
I2020-11-28 14:30:11,123 gigabyte-geforce-rtx-2070-super-gv-n207swf3oc-8gd: still in stock at the same price
I2020-11-28 14:30:13,143 gigabyte-geforce-rtx-3070-gv-n3070aorus-m-8gd: not in stock
I2020-11-28 14:30:15,113 gigabyte-geforce-rtx-3070-gv-n3070eagle-8gd: not in stock
I2020-11-28 14:30:17,111 gigabyte-geforce-rtx-3070-gv-n3070eagle-oc-8gd: not in stock
I2020-11-28 14:30:19,117 gigabyte-geforce-rtx-3070-gv-n3070gaming-oc-8gd: not in stock
I2020-11-28 14:30:21,094 gigabyte-geforce-rtx-3070-gv-n3070vision-oc-8gd: not in stock

```

**Comment by EricJMarti** [comment]
Great idea! Working on it now.

**Comment by EricJMarti** [comment]
Just committed a change to `docker_run.bash` with these suggestions. Thanks!
