### ISSUE TITLE
Amazon.ca, could not convert string to float: 'CDN\xa01313.34

### ISSUE THREAD

**Issue by MRizkBV** [EricJMarti/inventory-hunter#97]
I tried editing docker file changing all en_US to en_CA but this doesn't seem to do it. Any other suggestions?

**Comment by EricJMarti** [comment]
Can you try again with the latest image? I recently committed a change that was intended to ignore currency symbols.

**Comment by MRizkBV** [comment]
> Can you try again with the latest image? I recently committed a change that was intended to ignore currency symbols.

Fixed! <3
